#!/bin/bash
#
# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.
{% from 'vars/globals.map.jinja' import GLOBALS %}

NOROOT=1
. /usr/sbin/so-common

set_version
set_os
salt_minion_count

set -e

curl --retry 5 --retry-delay 60 -A "reposync/$VERSION/$OS/$(uname -r)/$MINIONCOUNT" https://sigs.securityonion.net/checkup --output /tmp/checkup
{% if GLOBALS.os == 'OEL' %}
dnf reposync --norepopath -g --delete -m --newest-only -c /opt/so/conf/reposync/repodownload.conf --repoid=securityonionsync --download-metadata -p /nsm/repo/

SALTVERSION=$(egrep 'version: [0-9]{4}' $DEFAULT_SALT_DIR/salt/salt/master.defaults.yaml | sed 's/^.*version: //')
DOCKERCE=$(grep -A2 'dockerce' $DEFAULT_SALT_DIR/salt/docker/version.yaml| grep -A1 'oracle' | awk '{print $2}')
CONTAINERD=$(grep -A2 'containerd' $DEFAULT_SALT_DIR/salt/docker/version.yaml| grep -A1 'oracle' | awk '{print $2}')
LOCKED_PKGS=(
  	"docker-ce-$DOCKERCE"
	"docker-ce-cli-$DOCKERCE"
	"docker-ce-rootless-extras-$DOCKERCE"
	"containerd.io-$CONTAINERD"
	"salt-$SALTVERSION"
	"salt-minion-$SALTVERSION"
	"salt-master-$SALTVERSION"
)
dnf download -c /opt/so/conf/reposync/repodownload.conf --repoid=securityonionsync --downloaddir=/nsm/repo/ ${LOCKED_PKGS[*]}
createrepo /nsm/repo
{% endif %}
